on:
  push:
    branches:
    - master
name: Build and Publish
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      uses: actions/npm@1.0.0
      with:
        entrypoint: yarn
        args: install
    - name: Only Master
        
    - name: build
      uses: actions/npm@1.0.0
      with:
        entrypoint: yarn
        args: build
    - name: Configure Website Bucket
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 website s3://${{ secrets.AWS_BUCKET_NAME }} --region eu-central-1 --index-document
          index.html
    - name: upload
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 sync ./dist s3://${{ secrets.AWS_BUCKET_NAME }} --region eu-central-1
