on: push
name: Build and Publish
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      uses: actions/npm@1.0.0
      with:
        entrypoint: yarn
        args: install
    - name: Only Master
      uses: actions/bin/filter@b2bea0749eed6beb495a8fa194c071847af60ea1
      with:
        args: branch master
    - name: build
      uses: actions/npm@1.0.0
      with:
        entrypoint: yarn
        args: build
    - name: Configure Website Bucket
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 website s3://slack-spring-boot.kreait.dev --region eu-central-1 --index-document
          index.html
    - name: upload
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 sync ./dist s3://slack-spring-boot.io --region eu-central-1
